env:
  LC_ALL: en_US.UTF-8
  REPOSITORY_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}
  REPOSITORY_USERNAME: ${{ secrets.REPOSITORY_USERNAME }}
jobs:
  build:
    name: build on OpenJDK Linux (just changing name for testing with new commit)
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      run: ./gradlew --parallel build
      shell: bash
    - continue-on-error: true
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: '*/target/reports'
name: build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
