jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      run: 'brew install gmp

        export HOMEBREW_NO_INSTALL_CLEANUP=true

        brew install docker

        colima start

        ./gradlew --parallel compileJava

        make -C org.alloytools.pardinus.native/native-code install

        colima stop

        '
    - continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: native
        path: org.alloytools.pardinus.native/native/
name: subflow-native
on:
  repository_dispatch:
    types: trigger-ga___subflow-native.yaml
