jobs:
  electrod:
    uses: ./.github/workflows/subflow-electrod.yaml
  merge-natives:
    needs:
    - electrod
    - native
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true
        path: org.alloytools.pardinus.native/native
    - continue-on-error: true
      run: 'git config user.name github-actions

        git config user.email github-actions@galloytools.org

        '
    - continue-on-error: true
      uses: peter-evans/create-pull-request@v6
      with:
        base: master
        branch: native
        commit-message: Native code update request
        delete-branch: true
        title: Native code update
        token: ${{ secrets.GITHUB_TOKEN }}
  native:
    uses: ./.github/workflows/subflow-native.yaml
name: trigger-native
on:
  repository_dispatch:
    types: trigger-ga___trigger-native.yaml
